name: Run Python Script
on:
  schedule:
    # 每5分钟运行一次（UTC时间）
    - cron: '*/5 * * * *'
jobs:
  execute:
    runs-on: ubuntu-latest  # 必须使用Linux环境
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run Python script
      env:
        BID_SECRET: ${{ secrets.BID_TEST }} 
      run: python scripts/BidFiveM.py
