name: Run Python Script
on:
  schedule:
    # 每5分钟运行一次（UTC时间）
    - cron: '*/5 * * * *'
  workflow_dispatch:  # 允许手动触发
jobs:
  execute:
    runs-on: ubuntu-latest  # 必须使用Linux环境
    env:
      TZ: Asia/Shanghai  # 设置时区
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
        pip freeze > requirements.txt  # 生成依赖清单
        
    - name: Run Python script
      env:
        BID_SECRET: ${{ secrets.BID_TEST }} 
      run: python scripts/BidFiveM.py
    
    - name: Archive logs
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: |
          *.log
          scripts/output/
          requirements.txt
          
    - name: Cache artifact upload
      uses: actions/upload-artifact@v4
      with:
        name: artifact               # 产物名称
        path: |                      # ✅ 必需参数（添加此项）
          scripts/output/*.log       # 日志文件路径
        retention-days: 3  # 自动清理旧日志（减少存储消耗）
        compression-level: 9  # 最高压缩比
        if-no-files-found: warn      # 无文件时警告
